### PR TITLE
Run validation and tests on Travis

### PR DESCRIPTION
**Pull request by skitt**
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
This is expected to fail — I want to check whether validation fails the build. I’ll push the fixed commit later so we can merge this.

**Comment by mangelajo** [comment]
ha, what happens if we run make ci, then make e2e ?  @dimaunx thoughts?

**Comment by mangelajo** [comment]
I see the unit tests: https://travis-ci.com/submariner-io/submariner/builds/119282452#L1219 but not the other parts of validation executing :? hmmm

**Comment by dimaunx** [comment]
> ha, what happens if we run make ci, then make e2e ? @dimaunx thoughts?

Should be fine.

**Comment by dimaunx** [comment]
We can run in parallel both of them similar to https://hackernoon.com/parallelizing-builds-in-travis-ci-9d913e5722eb

**Comment by skitt** [comment]
> I see the unit tests: https://travis-ci.com/submariner-io/submariner/builds/119282452#L1219 but not the other parts of validation executing :? hmmm

The validation is silent when it passes. Make runs all its targets one after the other, so saying `make ci e2e status=keep` is equivalent to `make ci status=keep && make e2e status=keep`.

I had deliberately left a validation failure in the first iteration of this patch, to verify that it did fail; but I can’t find that build any more. I’ll re-push the failing version and link the failed build for posterity.

**Pull request merged**
