### PR TITLE
Remove sourcing cluster_settings since it has been deleted

### PR DESCRIPTION
**Pull request by Billy99**
`cluster settings` was removed by [shipyard#668](https://github.com/submariner-io/shipyard/pull/668) but is still being sourced by reload-images.

Fixes the following:
```
$ cd submariner
$ make reload-images
:
Must remake target 'reload-images'.
./scripts/reload-images --restart all
Running with: restart=all
[16:50:25.480] [submariner]$ source /opt/shipyard/scripts/lib/deploy_funcs
[16:50:25.485] [submariner]$ . /opt/shipyard/scripts/lib/source_only
[16:50:25.488] [submariner]$ script_name=deploy_funcs
[16:50:25.493] [submariner]$ exec_name=reload-images
[16:50:25.498] [submariner]$ source /opt/shipyard/scripts/lib/utils
[16:50:25.502] [submariner]$ . /opt/shipyard/scripts/lib/source_only
[16:50:25.506] [submariner]$ script_name=utils
[16:50:25.509] [submariner]$ exec_name=reload-images
[16:50:25.514] [submariner]$ source /opt/shipyard/scripts/lib/cluster_settings
./scripts/reload-images: line 19: /opt/shipyard/scripts/lib/cluster_settings: No such file or directory
make: *** [Makefile:73: reload-images] Error 1
[16:50:25.523] [submariner]$ make --debug=b reload-images
make: *** [Makefile.dapper:43: reload-images] Error 2
```

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>

### CODE REVIEW

**Review by anfredette — APPROVED** [review]
This works for me.

**Comment by sridhargaddam** [comment]
> `cluster settings` was removed by #668 but is still being sourced by reload-images.

Looks like #668 is not the PR that removed cluster settings. Can you update it to the correct PR.

**Comment by Billy99** [comment]
> > `cluster settings` was removed by #668 but is still being sourced by reload-images.
> 
> Looks like #668 is not the PR that removed cluster settings. Can you update it to the correct PR.

@sridhargaddam Sorry, not use to working in multiple repos: [shipyard#668](https://github.com/submariner-io/shipyard/pull/668)
Commit message update.

**Comment by sridhargaddam** [comment]
> > Looks like #668 is not the PR that removed cluster settings. Can you update it to the correct PR.
> @sridhargaddam Sorry, not use to working in multiple repos: [shipyard#668](https://github.com/submariner-io/shipyard/pull/668) Commit message update.

no problem @Billy99. Thanks for fixing it.

**Review by sridhargaddam — APPROVED** [review]

**Comment by sridhargaddam** [comment]
@Billy99 i think you updated the PR and missed the commit message. Please update the commit message as well.

**Review by sridhargaddam — CHANGES_REQUESTED** [review]
Looks good, the commit message needs to be updated. Thanks for the fix @Billy99

**Review by sridhargaddam — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Pull request merged**
