### PR TITLE
Fix E2E test for globalnet w/ external network to handle multiple egressIPs

### LINKED ISSUE #1554: E2E test for globalnet w/ external network fails due to lack of handling multiple egressIPs
**What happened**:
`[external-dataplane] Connectivity` `should be able to connect from an external app to a pod in a cluster` E2E test fails

**What you expected to happen**:
`[external-dataplane] Connectivity` `should be able to connect from an external app to a pod in a cluster` E2E test succeeds

**How to reproduce it (as minimally and precisely as possible)**:

Run below command:
```
make e2e using=external-net,globalnet
```

**Anything else we need to know?**:

It happens due to lack of the logic similar to https://github.com/submariner-io/submariner/blob/b4625514061c1d85c10432a78ca0ad46e679367a/test/e2e/framework/dataplane.go#L174-L179

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mkimuram**
This PR fixes `[external-dataplane] Connectivity` `should be able to connect from an external app to a pod in a cluster` E2E test.

fixes: #1554

### CODE REVIEW

**Comment by mkimuram** [comment]
Tested locally with `make e2e using=external-net,globalnet` and it succeeds with below console logs:

<details>

```bash
=== RUN   TestE2E
Running Suite: Submariner E2E suite
===================================
Random Seed: 1631815481 - Will randomize all specs
Will run 1 of 1 specs

STEP: Creating kubernetes clients
[external-dataplane] Connectivity
  should be able to connect from an external app to a pod in a cluster
  /go/src/github.com/submariner-io/submariner/test/external/dataplane/connectivity.go:46
STEP: Creating namespace objects with basename "ext-dataplane"
STEP: Generated namespace "e2e-tests-ext-dataplane-tq296" in cluster "cluster2" to execute the tests in
STEP: Creating namespace "e2e-tests-ext-dataplane-tq296" in cluster "cluster1"
STEP: Creating a service without selector and endpoints in cluster "cluster1"
STEP: Creating a pod and a service in cluster "cluster2"
STEP: Sending an http request from external app "172.117.0.4" to the service "242.254.2.253" in the cluster "cluster2"
STEP: Verifying the pod received the request from one of egressGlobalIPs [242.254.1.1 242.254.1.2 242.254.1.3 242.254.1.4 242.254.1.5 242.254.1
.6 242.254.1.7 242.254.1.8]
Sep 16 18:05:07.069: INFO: 242.254.1.8 - - [16/Sep/2021 18:05:07] code 404, message File not found
242.254.1.8 - - [16/Sep/2021 18:05:07] "GET /e2e-tests-ext-dataplane-tq296cluster2 HTTP/1.1" 404 -

STEP: Sending an http request from the test pod "customd9knc" in cluster "cluster2" to the external app's ingressGlobalIP "242.254.1.253"
STEP: Verifying that external app received request from one of egressGlobalIPs [242.254.2.1 242.254.2.2 242.254.2.3 242.254.2.4 242.254.2.5 242
.254.2.6 242.254.2.7 242.254.2.8]
Sep 16 18:05:07.401: INFO: 242.254.2.3 - - [16/Sep/2021 18:05:07] code 404, message File not found
242.254.2.3 - - [16/Sep/2021 18:05:07] "GET /e2e-tests-ext-dataplane-tq296cluster2 HTTP/1.1" 404 -

STEP: Creating a pod and a service in cluster "cluster1"
STEP: Sending an http request from external app "172.117.0.4" to the service "242.254.1.252" in the cluster "cluster1"
STEP: Verifying the pod received the request from one of egressGlobalIPs [242.254.1.1 242.254.1.2 242.254.1.3 242.254.1.4 242.254.1.5 242.254.1
.6 242.254.1.7 242.254.1.8]
Sep 16 18:05:27.983: INFO: 172.117.0.4 - - [16/Sep/2021 18:05:27] code 404, message File not found
172.117.0.4 - - [16/Sep/2021 18:05:27] "GET /e2e-tests-ext-dataplane-tq296cluster1 HTTP/1.1" 404 -

STEP: Sending an http request from the test pod "customcrzgn" in cluster "cluster1" to the external app's ingressGlobalIP "242.254.1.253"
STEP: Verifying that external app received request from one of egressGlobalIPs [242.254.1.1 242.254.1.2 242.254.1.3 242.254.1.4 242.254.1.5 242.254.1.6 242.254.1.7 242.254.1.8]
Sep 16 18:05:28.314: INFO: 242.254.2.3 - - [16/Sep/2021 18:05:07] code 404, message File not found
242.254.2.3 - - [16/Sep/2021 18:05:07] "GET /e2e-tests-ext-dataplane-tq296cluster2 HTTP/1.1" 404 -
172.117.0.3 - - [16/Sep/2021 18:05:28] code 404, message File not found
172.117.0.3 - - [16/Sep/2021 18:05:28] "GET /e2e-tests-ext-dataplane-tq296cluster1 HTTP/1.1" 404 -

STEP: Deleting namespace "e2e-tests-ext-dataplane-tq296" on cluster "cluster2"
STEP: Deleting namespace "e2e-tests-ext-dataplane-tq296" on cluster "cluster1"

• [SLOW TEST:47.148 seconds]
[external-dataplane] Connectivity
/go/src/github.com/submariner-io/submariner/test/external/dataplane/connectivity.go:43
  should be able to connect from an external app to a pod in a cluster
  /go/src/github.com/submariner-io/submariner/test/external/dataplane/connectivity.go:46
------------------------------
```

</details>

**Review by tpantelis — APPROVED** [review]

**Comment by mkimuram** [comment]
@sridhargaddam 

It is the fix for https://github.com/submariner-io/submariner/pull/1455 that is talked in the meeting long ago.

Note that `End to End Full / E2E (pull_request)` contains this test, but it seems that it is skipped in the CI for this PR. So, it would be better to run on CI before merging this PR.

**Review by sridhargaddam — APPROVED** [review]

**Comment by sridhargaddam** [comment]
> Note that `End to End Full / E2E (pull_request)` contains this test, but it seems that it is skipped in the CI for this PR. So, it would be better to run on CI before merging this PR.

@mkimuram As soon as there are two approvals, the E2e tests will be triggered. We can manually trigger the tests by adding the label ready-to-test as well.

**Comment by sridhargaddam** [comment]
The e2e failure was unrelated to this PR, retriggered the tests.

**Pull request merged**
