### PR TITLE
Backport to 0.13: Bump to Fedora 36

### PR DESCRIPTION
**Pull request by skitt**
See individual commits.

This is a backport of #1887.

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

**Comment by nyechiel** [comment]
@skitt DCO is failing. Also, I am not sure what about https://github.com/submariner-io/submariner/runs/7089715209?check_suite_focus=true

**Comment by sridhargaddam** [comment]
All the individual commits have the signoff but DCO is still failing?

**Review by sridhargaddam — APPROVED** [review]
Changes look good to me, however there are some CI failures which needs to be addressed.

**Comment by skitt** [comment]
I think the CI errors are the result of my mistake in specifying `devel` as the target branch initially, instead of `release-0.13`. They should fix themselves once another PR is merged on `release-0.13` and this PR can be rebased on top of it.

**Review by mkolesnik — APPROVED** [review]

**Comment by mkolesnik** [comment]
FYI close & reopen (by default) triggers the GHAs triggered by `pull_request`.

I also manually approved DCO (which seemed to be still stuck in the past even after reopen)

**Pull request merged**
