### PR TITLE
readme: add a section explaining about using kind test cluster

### PR DESCRIPTION
**Pull request by hunchback**
I extended the readme to now include creating a test/sample cluster using `kind`.

---
This change is [Reviewable](https://reviewable.io/reviews/submariner-io/submariner/214)

### CODE REVIEW

**Comment by mangelajo** [comment]
@hunchback Thanks a lot for the improvements to the doc, I need to test them and figure out some things..

Did you notice that by running "make e2e status=keep" you get it already with submariner on top?

Also @dimaunx is working on a tool to do that in "one line" it's like an addition on top of kind.

**Comment by hunchback** [comment]
> > _[Reviewable](https://reviewable.io/reviews/submariner-io/submariner/214)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hunchback)
> 
> _[README.md, line 118 at r1](https://reviewable.io/reviews/submariner-io/submariner/214#-LuAC_aY-Y-sUA8Icy8B:-LuAC_aY-Y-sUA8Icy8C:b3wgxjw) ([raw file](https://github.com/submariner-io/submariner/blob/28fbe3c6f3315781b98d3b35181f64f825a19ddc/README.md#L118)):_
> 
> > funciton use-context {
> 
> funciton->function

fixed

**Comment by hunchback** [comment]
> @hunchback Thanks a lot for the improvements to the doc, I need to test them and figure out some things..
> 
> Did you notice that by running "make e2e status=keep" you get it already with submariner on top?
> 
> Also @dimaunx is working on a tool to do that in "one line" it's like an addition on top of kind.

so I had a bunch of issues when running `make e2e status=keep` (Isome resulting in PRs I opened)  so I resorted to working through the sequence manually,  but more so the README serves as a guide to to setting up Submariner and having the section of creating a cluster with `kind` makes it complete (and testable)

**Comment by mangelajo** [comment]
@hunchback did you see my comment above? ^

**Comment by hunchback** [comment]
@mangelajo - sure, will try out subctl and report back any issues

**Comment by hunchback** [comment]
So for now I will close, and consider reopening after the updated documentations is released.

**Pull request closed without merging**
