### PR TITLE
Update dapper base to fedora:31 to get go 1.13.x

### PR DESCRIPTION
**Pull request by mangelajo**

### CODE REVIEW

**Comment by mangelajo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/submariner-io/submariner/239)

**Comment by skitt** [comment]
Could you push this as a separate branch, with only the Fedora bump?

**Comment by mangelajo** [comment]
Ooops, I sent a PR with all together, sorry

**Comment by mangelajo** [comment]
> Could you push this as a separate branch, with only the Fedora bump?

done!

**Comment by skitt** [comment]
This isn’t related to the failure here, but it’s possible that this will also involve https://github.com/golangci/golangci-lint/issues/658 which would be fixed by upgrading `golangci-lint` to v1.18.0.

**Comment by mkolesnik** [comment]
This was already done and also moved to shipyard, closing

**Pull request closed without merging**
