### PR TITLE
deprecate report-dir and reportDir usage

### PR DESCRIPTION
**Pull request by pinikomarov**
not needed since : https://github.com/onsi/ginkgo/pull/601

### CODE REVIEW

**Comment by mangelajo** [comment]
hey @pinikomarov thanks a lot for cleaning up :-) can you update depricate -> deprecate.

**Comment by manosnoam** [comment]
@pinikomarov  What about removing the redundant "-report-dir" CLI option from Shipyard framework ?
Can you also clean that up ?

**Comment by pinikomarov** [comment]
@mangelajo @manosnoam so are we good to go on with the commit here ?

**Comment by pinikomarov** [comment]
@mangelajo ping ? are we good here ?

**Pull request merged**
