### PR TITLE
Support for manual trigger of release image job

### PR DESCRIPTION
**Pull request by sridhargaddam**
We have seen instances where the release job does not get
triggered after a PR gets merged and because of this, the
devel image still points to some old commit which produces
inconsistent results. This PR includes support to manually
trigger the release job in such scenarios.

### CODE REVIEW

**Review by skitt — APPROVED** [review]
Excellent!

**Comment by sridhargaddam** [comment]
@dfarrell07 @skitt Currently I marked this job as WIP. If you see value in supporting manual triggering of release image jobs, I can enable it for review.

**Review by aswinsuryan — APPROVED** [review]

**Comment by sridhargaddam** [comment]
@tpantelis the CI jobs are failing with the following error. Is this something related to the recent e2e fixes that you were looking at?

```
Summarizing 1 Failure:
  [FAIL] [redundancy] Gateway fail-over tests when multiple gateway nodes are configured and fail-over is initiated [It] should activate the passive gateway and be able to connect from another cluster
  /go/pkg/mod/github.com/submariner-io/shipyard@v0.15.0-m4/test/e2e/framework/network_pods.go:196
```

**Comment by tpantelis** [comment]
> @tpantelis the CI jobs are failing with the following error. Is this something related to the recent e2e fixes that you were looking at?
> 
> ```
> Summarizing 1 Failure:
>   [FAIL] [redundancy] Gateway fail-over tests when multiple gateway nodes are configured and fail-over is initiated [It] should activate the passive gateway and be able to connect from another cluster
>   /go/pkg/mod/github.com/submariner-io/shipyard@v0.15.0-m4/test/e2e/framework/network_pods.go:196
> ```

Which job are you referring to?

I see [this one](https://github.com/submariner-io/submariner/actions/runs/4534706423/jobs/7989235871) recently failed..  My PR just wraps `AwaitGatewayFullyConnected` ensuring there's a new `Gateway` object created.  However it failed before the line I changed:

```
github.com/submariner-io/submariner/test/e2e/redundancy.testGatewayPodRestartScenario(0xc00011c948)
    	/go/src/github.com/submariner-io/submariner/test/e2e/redundancy/gateway_failover.go:98 +0x752
```

The connection to `cluster2` failed:

`Failed to await Gateway on "cluster1-worker" with status active and connections UP. Gateway "cluster1-worker" is active but cluster "cluster2" is not connected: Status: "error", Message: "Failed to successfully ping the remote endpoint IP \"242.254.2.254\""`

**Comment by dfarrell07** [comment]
> If you see value in supporting manual triggering of release image jobs, I can enable it for review.

What originally caused you to look into this? Might be good to include in the commit message.

**Comment by sridhargaddam** [comment]
> What originally caused you to look into this? Might be good to include in the commit message.

Recently we have seen that even after Tom's Service Import Aggregation PR got merged, the release job did not get triggered and AFAIR there were similar instances discussed on slack. Anyways, updated the commit message. Thanks for taking a look.

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Pull request merged**
