### PR TITLE
Fedora minimal

### PR DESCRIPTION
**Pull request by skitt**
This adds to #616.

### CODE REVIEW

**Comment by mkolesnik** [comment]
@skitt interestingly, the job had some errors when building the image (thought that didn't seem to fail the build itself, nor did it seem to affect e2e):
```
Thu, 04 Jun 2020 04:08:18 GMT Installing: unbound-libs;1.10.1-1.fc32;x86_64;updates
Thu, 04 Jun 2020 04:08:18 GMT /usr/bin/systemctl: error while loading shared libraries: libsystemd-shared-245.so: cannot open shared object file: No such file or directory
Thu, 04 Jun 2020 04:08:18 GMT Installing: libreswan;3.31-2.fc32;x86_64;updates
Thu, 04 Jun 2020 04:08:18 GMT /usr/bin/systemctl: error while loading shared libraries: libsystemd-shared-245.so: cannot open shared object file: No such file or directory
Thu, 04 Jun 2020 04:08:18 GMT Installing: strongswan;5.8.4-2.fc32;x86_64;updates
Thu, 04 Jun 2020 04:08:18 GMT /usr/bin/systemctl: error while loading shared libraries: libsystemd-shared-245.so: cannot open shared object file: No such file or directory
Thu, 04 Jun 2020 04:08:18 GMT Installing: procps-ng;3.3.15-7.fc32;x86_64;fedora
Thu, 04 Jun 2020 04:08:18 GMT Installing: iptables;1.8.4-7.fc32;x86_64;fedora
```

Do you think it's significant, given the tests passed regardless?

**Comment by mangelajo** [comment]
It should be fine as long as it’s working. I guess they don’t pack systemd for Fedora minimal and they are not looking at the warnings?

Enviado desde mi iPhone

**Comment by mkolesnik** [comment]
Yea as I said the image did build, and the e2e tests passed which is reassuring. Just pointing it out since it seemed odd to me (i.e. it says it's an error, but continues regardless)

**Comment by skitt** [comment]
> @skitt interestingly, the job had some errors when building the image (thought that didn't seem to fail the build itself, nor did it seem to affect e2e):
> 
> ```
> Thu, 04 Jun 2020 04:08:18 GMT Installing: unbound-libs;1.10.1-1.fc32;x86_64;updates
> Thu, 04 Jun 2020 04:08:18 GMT /usr/bin/systemctl: error while loading shared libraries: libsystemd-shared-245.so: cannot open shared object file: No such file or directory
> Thu, 04 Jun 2020 04:08:18 GMT Installing: libreswan;3.31-2.fc32;x86_64;updates
> Thu, 04 Jun 2020 04:08:18 GMT /usr/bin/systemctl: error while loading shared libraries: libsystemd-shared-245.so: cannot open shared object file: No such file or directory
> Thu, 04 Jun 2020 04:08:18 GMT Installing: strongswan;5.8.4-2.fc32;x86_64;updates
> Thu, 04 Jun 2020 04:08:18 GMT /usr/bin/systemctl: error while loading shared libraries: libsystemd-shared-245.so: cannot open shared object file: No such file or directory
> Thu, 04 Jun 2020 04:08:18 GMT Installing: procps-ng;3.3.15-7.fc32;x86_64;fedora
> Thu, 04 Jun 2020 04:08:18 GMT Installing: iptables;1.8.4-7.fc32;x86_64;fedora
> ```
> 
> Do you think it's significant, given the tests passed regardless?

It’s an over-enthusiastic `rm` in the minimal KS, see [here](https://kojipkgs.fedoraproject.org//packages/Fedora-Container-Minimal-Base/32/20200604.0/images/fedora-container-base-minimal.ks); we don’t need systemd in our containers so it doesn’t matter.

**Comment by skitt** [comment]
https://pagure.io/fedora-kickstarts/pull-request/650 will fix the `libsystemd-shared` error.

**Pull request merged**
