### PR TITLE
Globalnet flag adjustment

### PR DESCRIPTION
**Pull request by mkolesnik**
Since it was changed to a boolean flag, no need to send true/false

### CODE REVIEW

**Comment by dfarrell07** [comment]
Seems like a job failed on another sporadic failure. As we discussed on https://github.com/submariner-io/shipyard/pull/125, I raised an issue to try to track and maybe fix/work-around the issues: https://github.com/submariner-io/shipyard/pull/125. I retriggered the job.

**Comment by mkolesnik** [comment]
> Seems like a job failed on another sporadic failure. As we discussed on [submariner-io/shipyard#125](https://github.com/submariner-io/shipyard/pull/125), I raised an issue to try to track and maybe fix/work-around the issues: #532. I retriggered the job.

Actually it seems that it didn't pick up the changes from Shipyard yet.. I restarted it

**Comment by dfarrell07** [comment]
> > Seems like a job failed on another sporadic failure. As we discussed on [submariner-io/shipyard#125](https://github.com/submariner-io/shipyard/pull/125), I raised an issue to try to track and maybe fix/work-around the issues: #532. I retriggered the job.
> 
> Actually it seems that it didn't pick up the changes from Shipyard yet.. I restarted it

Why would needing that change have broken the E2E tests here?

https://pastebin.com/0AWQt1pp

**Comment by mkolesnik** [comment]
> Would needing that change have broken the E2E tests like this?
> 
> https://pastebin.com/0AWQt1pp

Yes, as you can see in the log it tried a base image from 2 days ago:
```
[00:00:44.673532] Digest: sha256:6e5110cfac962868256c12f208d00c4bd75a6cbca5ae5b7307a32d2869e1e69a
```

**Comment by dfarrell07** [comment]
I see it failed again, at the end of the main tests this time. Copied the logs and doc'd on https://github.com/submariner-io/submariner/issues/532 before you retriggered it.

**Comment by mkolesnik** [comment]
> I see it failed again, at the end of the main tests this time. Copied the logs and doc'd on #532 before you retriggered it.

Yeah that one wasn't even related to shipyard, so those logs won't be of any help.

Anyhoo those intermittent failures sure are annoying, we'll see what we can do but I don't think it'll be too much given the number of factors that can fail.

**Comment by dfarrell07** [comment]
> > I see it failed again, at the end of the main tests this time. Copied the logs and doc'd on #532 before you retriggered it.
> 
> Yeah that one wasn't even related to shipyard, so those logs won't be of any help.
> 
> Anyhoo those intermittent failures sure are annoying, we'll see what we can do but I don't think it'll be too much given the number of factors that can fail.

The goal isn't to diagnose the underlying problem with the logs, just to collect an overview of the failures so we can start to understand the broad types of flaky failures we're seeing.

**Pull request merged**
