### PR TITLE
add kubeovn into plugin constants

### PR DESCRIPTION
**Pull request by lut777**
It's a patch PR.
In submariner-operator I need to add network cluster discover function for CNI KubeOVN. To mark the CNI in ClusterNetwork, I need this constant variable.
This PR will not introduce any test.

### CODE REVIEW

**Review by skitt — COMMENTED** [review]
Will this not need any special handling in the route agent, if only to add the CNI to the list of network plugins? `GetNetworkPlugins` in `pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go`.

**Comment by lut777** [comment]
> Will this not need any special handling in the route agent, if only to add the CNI to the list of network plugins? `GetNetworkPlugins` in `pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go`.

Not now. currently I intend to continue the dataplane of Submariner first. 
I will not make any changes until the evaluating of ovn-kubernetes' solution and ours solution,

**Comment by lut777** [comment]
@skitt Are there any other issues that need to be addressed?

**Comment by dfarrell07** [comment]
@lut777 is this blocking your K-OVN work? Still planning on working on this?

**Pull request closed without merging**
