### PR TITLE
Bump K8s to 0.24.2

### PR DESCRIPTION
**Pull request by tpantelis**

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Comment by tpantelis** [comment]
The GW pod is getting this error: 

`leaderelection.go:330] error retrieving resource lock submariner-operator/submariner-gateway-lock: leases.coordination.k8s.io "submariner-gateway-lock" is forbidden: User "system:serviceaccount:submariner-operator:submariner-gateway" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "submariner-operator"`

It seems we need to add a permission to the SA.

**Comment by dfarrell07** [comment]
I guess this is related to https://github.com/stolostron/submariner-addon/pull/420.

**Comment by tpantelis** [comment]
Hopefully https://github.com/submariner-io/submariner-operator/pull/2138 will take care of it completely.

**Comment by tpantelis** [comment]
The upgrade job is still failing with the same permissions error b/c it's using the latest `subctl` version (v0.12.2) when it runs join with the locally built images. 

```
[15:44:44.468] [submariner]$ [cluster2] subctl version
subctl version: v0.12.2
```

The previous/latest version of `subctl` is installed in _/root/.local/bin_ and the current `subctl` is installed in _/go/bin_.  When deploying the previous/latest it specifically runs the `subctl` installed in the  _/root/.local/bin_ but, when deploying the current version, it runs `subctl` sans the path. The problem is that `Dockerfile.shipyard-dapper-base` defines $PATH as:

`PATH=/root/.local/bin:/go/bin:/usr/local/go/bin`

so it picks the one in _/root/.local/bin_. This path was added by the recent [OVN changes.](https://github.com/submariner-io/shipyard/pull/704/commits/72301efcf47a161b035e0f9927572167cbf524be) (@astoycos ). A simple solution is to move _/go/bin_ before _/root/.local/bin_ (https://github.com/submariner-io/shipyard/pull/872).

**Review by nyechiel — APPROVED** [review]

**Pull request merged**
