### PR TITLE
Remove wait-for-node-ready in GW and RA main

### LINKED ISSUE #3274: Add a “wait for node readiness” binary and image
Given that several binaries now offer “wait for node readiness” variant executions, it seems like it would be useful to move that to a single, separate, much simpler binary and use that in init containers.

### PR DESCRIPTION
**Pull request by tpantelis**
This is now handled by the separate await-node-ready binary.

Fixes https://github.com/submariner-io/submariner-operator/issues/3274

### CODE REVIEW

**Review by skitt — CHANGES_REQUESTED** [review]
The commit message and PR description mention GW, but this only touches RA.

**Comment by tpantelis** [comment]
> The commit message and PR description mention GW, but this only touches RA.

It changes the top-level _main.go_ as well.

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
> > The commit message and PR description mention GW, but this only touches RA.
> 
> It changes the top-level _main.go_ as well.

So it does, I’m blind :roll_eyes:

**Comment by skitt** [comment]
Ah, what misled me is that I thought this could remove `WaitForLocalNodeReady` entirely.

**Review by aswinsuryan — APPROVED** [review]

**Pull request merged**
