### PR TITLE
Add E2E with IPv4/6 dual-stack job

### PR DESCRIPTION
**Pull request by dfarrell07**
As discussed on a call, this adds E2E test coverage for the new dual-stack deployment logic. We have deployment test coverage in Shipyard, but we should also run E2E tests in the repo with the most relevant code.

### CODE REVIEW

**Comment by dfarrell07** [comment]
Maybe we should also remove the E2E external-net, globalnet job from PRs if it's always failing.

**Review by skitt — CHANGES_REQUESTED** [review]
It would be worth running dual-stack and dual-stack with Globalnet, since the latter changes the network expectations quite a lot.

**Comment by dfarrell07** [comment]
Something weird is going on, I pushed an update to my branch but it's not showing up on the PR. The PR did get marked as not needing a rebase, but the new changes aren't showing.

**Comment by dfarrell07** [comment]
The new commit is there on my branch that's linked from the top of this PR: https://github.com/dfarrell07/submariner/commit/0fdd5874a7b7a285502aa7efdfbf8b8f1af13f79

**Comment by dfarrell07** [comment]
The changes finally showed up here.

GitHub's status was green, but clearly not.

**Comment by dfarrell07** [comment]
@skitt this is ready for re-review

**Review by skitt — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by tpantelis** [comment]
It seems none of the E2E jobs are running and the dual-stack jobs aren't even listed.

**Comment by skitt** [comment]
> It seems none of the E2E jobs are running and the dual-stack jobs aren't even listed.

They are now ;-).

**Pull request merged**
