### PR TITLE
Add CodeQL variant analysis scanning

### PR DESCRIPTION
**Pull request by dfarrell07**
This is a different type of static analysis than others we run.

> Variant analysis is the process of using a known security
vulnerability as a seed to find similar problems in your code.

https://codeql.github.com/docs/codeql-overview/about-codeql/

CodeQL doesn't only do variant analysis for security issues, it also has semantic queries/rules for other types of issues.

https://github.com/github/codeql/tree/main/go/ql/src

It identified new issues (already fixed) that our other tools missed.

The company that built it was bought by GitHub and the tool is being integrated into GitHub's security workflow.

Add one unprivileged version of the job to gate PRs and one privileged version on-merge to report results.

Relates-to: #1970
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
There's still an issue with reproducing negative results: https://github.com/submariner-io/submariner/issues/1970#issuecomment-1262571853

But checks are clearly running, and I think we're using the GHA as we should be. Maybe it's okay to merge?

**Comment by skitt** [comment]
Could you try adding a code change that this should flag, just to check whether it finds issues?

**Comment by dfarrell07** [comment]
> Could you try adding a code change that this should flag, just to check whether it finds issues?

Yeah, that's what I was doing to try to reproduce negative results. One example (there are others linked in the tracking issue): https://github.com/dfarrell07/submariner/pull/54

**Comment by dfarrell07** [comment]
> > Could you try adding a code change that this should flag, just to check whether it finds issues?
> 
> Yeah, that's what I was doing to try to reproduce negative results. One example (there are others linked in the tracking issue): [dfarrell07#54](https://github.com/dfarrell07/submariner/pull/54)

Better example based on exactly this change: https://github.com/dfarrell07/submariner/pull/56

**Comment by skitt** [comment]
> Better example based on exactly this change: [dfarrell07#56](https://github.com/dfarrell07/submariner/pull/56)

Where are the results supposed to show up? The check says “No new or fixed alerts” which suggests it didn’t find anything amiss.

**Comment by dfarrell07** [comment]
> > Better example based on exactly this change: [dfarrell07#56](https://github.com/dfarrell07/submariner/pull/56)
> 
> Where are the results supposed to show up? The check says “No new or fixed alerts” which suggests it didn’t find anything amiss.

Right, that's the issue, we fixed all the issues flagged by CodeQL (run through LGTM.com) before I was able to verify the negative case. I the linked example I revert a fix and it still passes.

**Comment by tpantelis** [comment]
Is this PR still relevant?

**Comment by dfarrell07** [comment]
> Is this PR still relevant?

I'd still like to merge it as I think it's helpful, I just can't show it's actually catching issues. So to be explicit, I'd like to merge it although it's a bit below the quality standard I typically strive for.

**Comment by tpantelis** [comment]
> I'd still like to merge it as I think it's helpful, I just can't show it's actually catching issues. So to be explicit, I'd like to merge it although it's a bit below the quality standard I typically strive for.

I see that [submariner-operator](https://github.com/submariner-io/submariner-operator/actions/runs/4105824558/jobs/7083225358) is already running this tool.  But I'm not clear on where we can view or use the results...

**Comment by dfarrell07** [comment]
> > I'd still like to merge it as I think it's helpful, I just can't show it's actually catching issues. So to be explicit, I'd like to merge it although it's a bit below the quality standard I typically strive for.
> 
> I see that [submariner-operator](https://github.com/submariner-io/submariner-operator/actions/runs/4105824558/jobs/7083225358) is already running this tool. But I'm not clear on where we can view or use the results...

It publishes SARIF reports that GitHub automatically consumes and shows in the Security tab.

https://github.com/submariner-io/submariner-operator/security/code-scanning?query=branch%3Adevel+tool%3ACodeQL+

**Review by tpantelis — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Pull request merged**
