### PR TITLE
refactor: rename submariner-engine to submariner-gateway

### PR DESCRIPTION
**Pull request by SteveMattar**
Signed-off-by: Steve Mattar <smattar@redhat.com>

### CODE REVIEW

**Comment by SteveMattar** [comment]
don't merge before https://github.com/submariner-io/shipyard/pull/462

**Comment by dfarrell07** [comment]
This needs a manual rebase.

**Review by dfarrell07 — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]

**Comment by mangelajo** [comment]
This has been up for 13 days, so setting up auto-merge

**Comment by SteveMattar** [comment]
@mangelajo after the binary rename we now need this https://github.com/submariner-io/submariner-operator/pull/1163

**Pull request merged**
