### PR TITLE
Do not merge: Testing CI failures

### PR DESCRIPTION
**Pull request by sridhargaddam**

### CODE REVIEW

**Comment by sridhargaddam** [comment]
All CI jobs PASSED after changing the Docker fedora versions to F36.

**Comment by sridhargaddam** [comment]
All CI jobs passed for the second time. Triggering another run and this time running even the redundancy tests as well.
Screenshot from 2023-04-24 12-34-05

**Comment by skitt** [comment]
I’ve opened https://github.com/submariner-io/submariner/pull/2443 to see if we get the same failures with Fedora 38; if not, we might want to bump to that.

I wonder if this could be related to changes in Libreswan; F36 has 4.9, F37 and F38 have 4.10.

**Comment by sridhargaddam** [comment]
> I’ve opened #2443 to see if we get the same failures with Fedora 38; if not, we might want to bump to that.
> 
> I wonder if this could be related to changes in Libreswan; F36 has 4.9, F37 and F38 have 4.10.

Lets see. I just triggered a "ready-to-test" on the F38 patch, will keep a watch on the e2e status.

**Comment by sridhargaddam** [comment]
Update: The issue was narrowed down to Fedora 37. After we migrate to F38, we see that all the tests are passing successfully.
https://github.com/submariner-io/submariner/pull/2443

**Pull request closed without merging**
