### PR TITLE
Unpin Kubernetes dependencies

### PR DESCRIPTION
**Pull request by skitt**
This doesn't seem to break anything, and helps with go install (see
<https://github.com/golang/go/issues/44840>).

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
I've tried re-running the UTs 6 times now, all 6 failed. :skull:

**Comment by skitt** [comment]
> I've tried re-running the UTs 6 times now, all 6 failed. skull

Yes, the errors here are related to `GlobalIngressIP` and are tied to the PR; they’re not the pinger error we’re getting on other PRs.

**Comment by nyechiel** [comment]
@skitt I assume we want this fixed for 0.12?

**Comment by skitt** [comment]
> @skitt I assume we want this fixed for 0.12?

I would have liked it fixed for 0.12, but it’s too complex! We’ll have to punt it to 0.13.

**Comment by tpantelis** [comment]
This PR is outdated and no longer needed.

**Pull request closed without merging**
