### PR TITLE
e2e: fix kind cluster apiserver port only for kubefed

### PR DESCRIPTION
**Pull request by hunchback**
This change is [Reviewable](https://reviewable.io/reviews/submariner-io/submariner/221)

### CODE REVIEW

**Comment by hunchback** [comment]
I did this to bypass error `Reason: Get http://<IP>:6443/version: dial tcp <IP>:6443: i/o timeout` which I was getting when running `make ci e2e status=keep`

**Comment by mangelajo** [comment]
This change breaks CI: 

https://travis-ci.com/submariner-io/submariner/builds/136954091#L1738

Can you report a Github issue with the details to reproduce what you were experience?, then we can get @dimaunx to help us with the fix.

**Comment by dimaunx** [comment]
@hunchback how this can reproduced locally? It never happens to me when running make ci e2e status=keep multiple times.

**Comment by hunchback** [comment]
> @hunchback how this can reproduced locally? It never happens to me when running make ci e2e status=keep multiple times.

Was not able to reproduce (after rebasing), thus closing

**Pull request closed without merging**
