### PR TITLE
Update wireguard version

### PR DESCRIPTION
**Pull request by tpantelis**
Bump to the latest version of `golang.zx2c4.com/wireguard/wgctrl`.

<details>
  <summary>Background</summary>

 The release process fails to update the **submariner** version in the **submariner-operator** and **subctl** repos due to a failure retrieving the _wireguard_ dependency:

```
[19:20:10.103] [dir=submariner-operator; fn=_update_go_mod]$ GOPROXY=direct go get [github.com/submariner-io/submariner@v0.14.0-m2](http://github.com/submariner-io/submariner@v0.14.0-m2)
go: downloading [github.com/submariner-io/submariner](http://github.com/submariner-io/submariner) v0.14.0-m2
go: downloading [github.com/go-ping/ping](http://github.com/go-ping/ping) v0.0.0-20210506233800-ff8be3320020
go: downloading [github.com/vishvananda/netlink](http://github.com/vishvananda/netlink) v1.1.1-0.20210518155637-4cb3795f2ccb
go: downloading [golang.zx2c4.com/wireguard/wgctrl](http://golang.zx2c4.com/wireguard/wgctrl) v0.0.0-20211215182854-7a385b3431de
go: downloading [golang.zx2c4.com/wireguard](http://golang.zx2c4.com/wireguard) v0.0.0-20211129173154-2dd424e2d808
go: downloading [golang.org/x/sync](http://golang.org/x/sync) v0.0.0-20220722155255-886fb9371eb4
go: downloading [github.com/vishvananda/netns](http://github.com/vishvananda/netns) v0.0.0-20200728191858-db3c7e526aae
go: downloading [honnef.co/go/tools](http://honnef.co/go/tools) v0.2.2
go: downloading [github.com/mdlayher/genetlink](http://github.com/mdlayher/genetlink) v1.1.0
go: downloading [github.com/mdlayher/netlink](http://github.com/mdlayher/netlink) v1.4.2
go: downloading [github.com/josharian/native](http://github.com/josharian/native) v0.0.0-20200817173448-b6b71def0850
go: downloading [github.com/mdlayher/socket](http://github.com/mdlayher/socket) v0.0.0-20211102153432-57e3fa563ecb
go: downloading [github.com/BurntSushi/toml](http://github.com/BurntSushi/toml) v0.4.1
go: [golang.zx2c4.com/wireguard@v0.0.0-20211129173154-2dd424e2d808](http://golang.zx2c4.com/wireguard@v0.0.0-20211129173154-2dd424e2d808) requires
	[golang.zx2c4.com/go118/netip@v0.0.0-20211111135330-a4a02eeacf9d](http://golang.zx2c4.com/go118/netip@v0.0.0-20211111135330-a4a02eeacf9d): unrecognized import path "[golang.zx2c4.com/go118/netip](http://golang.zx2c4.com/go118/netip)": reading https://golang.zx2c4.com/go118/netip?go-get=1: 404 Not Found
```

It's unclear why this happens during release and not when building submariner but the latest _wireguard_ version doesn’t pull in [golang.zx2c4.com/go118/netip](http://golang.zx2c4.com/go118/netip) so hopefully this will fix it. Either way, it's beneficial to keep third party libs up-to-date with latest versions.

</details>

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]
Do we know why Dependabot didn't send this upgrade?

**Comment by tpantelis** [comment]
> Do we know why Dependabot didn't send this upgrade?

I'm not sure but where it's hosted on golang.zx2c4.com doesn't appear to be a "normal" github repo so I suspect Dependabot doesn't know how to handle it.

**Comment by skitt** [comment]
Dependabot doesn’t suggest Wireguard bumps because the dependency has never been tagged upstream; Dependabot copes fine with git repositories outside GH.

**Review by skitt — APPROVED** [review]

**Comment by sridhargaddam** [comment]
> Dependabot doesn’t suggest Wireguard bumps because the dependency has never been tagged upstream; 

The [dependabot.yml ](https://github.com/submariner-io/submariner/blob/devel/.github/dependabot.yml) config does not seem to ignore the wireguard. Can you please elaborate where the dependency is not tagged?

**Comment by skitt** [comment]
> > Dependabot doesn’t suggest Wireguard bumps because the dependency has never been tagged upstream;
> 
> The [dependabot.yml ](https://github.com/submariner-io/submariner/blob/devel/.github/dependabot.yml) config does not seem to ignore the wireguard. Can you please elaborate where the dependency is not tagged?

https://golang.zx2c4.com/wireguard/wgctrl leads to https://github.com/WireGuard/wgctrl-go which has no tags (https://github.com/WireGuard/wgctrl-go/tags). Dependabot only bumps to tags (or GH releases, which end up being the same thing in git).

**Comment by sridhargaddam** [comment]
> > > Dependabot doesn’t suggest Wireguard bumps because the dependency has never been tagged upstream;
> > 
> > 
> > The [dependabot.yml ](https://github.com/submariner-io/submariner/blob/devel/.github/dependabot.yml) config does not seem to ignore the wireguard. Can you please elaborate where the dependency is not tagged?
> 
> https://golang.zx2c4.com/wireguard/wgctrl leads to https://github.com/WireGuard/wgctrl-go which has no tags (https://github.com/WireGuard/wgctrl-go/tags). Dependabot only bumps to tags (or GH releases, which end up being the same thing in git).

Got it, thanks for the details.

**Pull request merged**
