### PR TITLE
add option to setup cable driver on make e2e.

### PR DESCRIPTION
**Pull request by deanlorenz**
For example, 
```
make e2e cable_driver=wireguard
```

### CODE REVIEW

**Comment by deanlorenz** [comment]
For changes to work on dev environment:

- `scripts/` gets copied into  `/opt` during dapper-image creation; however `make dapper-image` does not check all dependencies, so the `scripts/...` changes will not make into image

- As a workaround, changing `scripts/e2e` wrapper to call `kind-e2e/e2e.sh` (remove `/opt` prefix) will use the scripts in local dev directory

- subctl version must be new enough to support the `cable-driver` option. `latest` is good.

**Comment by dfarrell07** [comment]
Thanks for the PRs! FYI, much of the related scripting is going to be extracted (for deduplication across projects via Shipyard) in https://github.com/submariner-io/submariner/pull/474.

**Comment by mangelajo** [comment]
Yes, let's add the patch in shipyard at the right moment, sorry about that ':)

**Comment by mkolesnik** [comment]
Closing as it has been added to shipyard https://github.com/submariner-io/shipyard/pull/102

**Pull request closed without merging**
