### PR TITLE
Enable OVN IC CI

### PR DESCRIPTION
**Pull request by dfarrell07**
This will be removed once we're ready to default to OVN IC.

Relates-to: https://github.com/submariner-io/enhancements/issues/209

### CODE REVIEW

**Comment by dfarrell07** [comment]
There seems to be an issue.

OVN IC:

```
2023-08-16T19:27:14.9265319Z Cluster settings::
2023-08-16T19:27:14.9266127Z   broker - 'cluster1'
2023-08-16T19:27:14.9266611Z   clusters - 'cluster1' 'cluster2'
2023-08-16T19:27:14.9267107Z   cni - ([cluster2]="" [cluster1]="" )
```

vs OVN:

```
2023-08-16T19:25:17.8719530Z Cluster settings::
2023-08-16T19:25:17.8720305Z   broker - 'cluster1'
2023-08-16T19:25:17.8720891Z   clusters - 'cluster1' 'cluster2'
2023-08-16T19:25:17.8721338Z   cni - ([cluster2]="ovn" [cluster1]="ovn" )
```

**Comment by aswinsuryan** [comment]
@dfarrell07 do we still have this issue? It would be great if we could get this merged as it can avoid any regression in ovn-ic.

**Comment by tpantelis** [comment]
Is this still relevant?

**Comment by aswinsuryan** [comment]
> Is this still relevant?

yes this is important for us, now IC implementation is not getting tested in CI

**Comment by tpantelis** [comment]
> > Is this still relevant?
> 
> yes this is important for us, now IC implementation is not getting tested in CI

OK then I assume this should be planned for 0.17 so I moved it to the board.

**Comment by tpantelis** [comment]
> > > Is this still relevant?
> > 
> > 
> > yes this is important for us, now IC implementation is not getting tested in CI
> 
> OK then I assume this should be planned for 0.17 so I moved it to the board.

Oh I see the enhancement is already on the board.

**Pull request closed without merging**
