### PR TITLE
Tweet "Hello, world" about new Twitter automation

### PR DESCRIPTION
**Pull request by dfarrell07**
Use the new "Twitter, Together" GHA to tweet about this new automation,
encourage community to use it.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
The tweet-test job seems to be working :heavy_check_mark: https://github.com/submariner-io/submariner/runs/4610506829?check_suite_focus=true

**Review by nyechiel — COMMENTED** [review]
@dfarrell07 I think it makes sense to add a link to the tweets folder

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
> @dfarrell07 I think it makes sense to add a link to the tweets folder

That'll be a good test of the tool's ability to use Twitter's link-shortener.

```
$ echo "Hello again, world! Submariner is now tweeting from .tweet files! We hope this means more content in our feed, curated by the commeet about? Send a PR" | wc -c
222
$ echo "Hello again, world! Submariner is now tweeting from .tweet files! We hope this means more content in our feed, curated by the commeet about? Send a PR https://github.com/submariner-io/submariner/tree/devel/tweets" | wc -c
284
```

**Comment by dfarrell07** [comment]
> That'll be a good test of the tool's ability to use Twitter's link-shortener.

It still passes validations, so I assume it'll work. :partying_face:

**Comment by nyechiel** [comment]
@dfarrell07 cool! There is a MD failure now

**Comment by dfarrell07** [comment]
> @dfarrell07 cool! There is a MD failure now

Yeah, we're in a busy queue behind https://github.com/submariner-io/submariner/pull/1648.

**Review by nyechiel — APPROVED** [review]

**Comment by nyechiel** [comment]
@dfarrell07 now we need a bot that will only merge these between noon to 1:00p.m EST for best exposure :laughing:

**Review by sridhargaddam — APPROVED** [review]

**Comment by dfarrell07** [comment]
It failed with

> [ { code: 215, message: 'Bad Authentication data.' } ]

https://github.com/submariner-io/submariner/runs/4715357398?check_suite_focus=true

I set up the Twitter secrets with @tpantelis a few weeks ago, I'll need to check that I guess.

**Pull request merged**
