### PR TITLE
Refactor utils functions

### PR DESCRIPTION
**Pull request by tpantelis**
Remove unused functions and move others elsewhere. See individual commits for details.

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
None of the removed function are used by dependencies (`submariner-operator` or `subctl`).

**Review by dfarrell07 — APPROVED** [review]

**Comment by nyechiel** [comment]
Is this require a backport?

**Comment by skitt** [comment]
> Is this require a backport?

No, I added it to the 0.13 board for tracking purposes but it’s really a 0.14 PR.

**Comment by tpantelis** [comment]
> > Is this require a backport?
> 
> No, I added it to the 0.13 board for tracking purposes but it’s really a 0.14 PR.

yeah it's just tech debt cleanup going forward.

**Comment by dfarrell07** [comment]
So let's go ahead and merge this into devel?

**Pull request merged**
