### PR TITLE
Add PR reviews link to committer request template

### PR DESCRIPTION
**Pull request by dfarrell07**
Add template for a link to a GH query that shows the PR reviews of a
user on a Submariner repository. Combine the two similar review sections
because in practice people have been answering both with a single link
like this.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Review by nyechiel — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
There seems to be an issue with the Go UTs at the moment, they are failing like this on various unrelated PRs.

**Comment by skitt** [comment]
> There seems to be an issue with the Go UTs at the moment, they are failing like this on various unrelated PRs.

Specifically, the pinger stop test is failing (the last test in `pinger_test.go`). The whole set of tests disables itself if it can’t run the pinger; this might be what changed — the tests don’t run locally, I don’t know if they used to run on CI or not.

**Comment by skitt** [comment]
> > There seems to be an issue with the Go UTs at the moment, they are failing like this on various unrelated PRs.
> 
> Specifically, the pinger stop test is failing (the last test in `pinger_test.go`). The whole set of tests disables itself if it can’t run the pinger; this might be what changed — the tests don’t run locally, I don’t know if they used to run on CI or not.

The test ran and passed here: https://github.com/submariner-io/submariner/runs/4461769158?check_suite_focus=true

**Comment by dfarrell07** [comment]
And re-running (I think the 3rd time), it passed here.

**Pull request merged**
