### PR TITLE
Alert user the supported terraform version in prep_for_subm.sh

### PR DESCRIPTION
**Pull request by sridhargaddam**
Currently, while preparing the AWS cluster for Submariner as
part of prep_for_subm.sh script, we only support terraform
version 12.x

In this PR, we display an appropriate error message if users
are trying to run the script with a different version of terraform.

Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

**Review by manosnoam — APPROVED** [review]

**Comment by mangelajo** [comment]
Actually we believe it has to be <=0.12.3 if we can check that

**Comment by sridhargaddam** [comment]
> Actually we believe it has to be <=0.12.3 if we can check that

I remember using v 0.12.12 (or something very close to that) and it worked.

**Review by tpantelis — APPROVED** [review]

**Comment by mangelajo** [comment]
> > Actually we believe it has to be <=0.12.3 if we can check that
> 
> I remember using v 0.12.12 (or something very close to that) and it worked.

I know noam had issues about duplicate security groups in later versions @manosnoam do you remember which one?

**Review by mangelajo — APPROVED** [review]

**Comment by tpantelis** [comment]
We can squash and merge to eliminate the DCO check failure.

**Comment by nyechiel** [comment]
@manosnoam what's your experience with the Terraform version? I ran some tests earlier this week, and **v0.12.3** is the only version that really worked smoothly for me.

**Comment by manosnoam** [comment]
For me 0.12.2 works

**Comment by sridhargaddam** [comment]
@nyechiel @manosnoam I just tried terraform 0.12.12 and it works fine :)

**Pull request merged**
