### PR TITLE
Bump to Fedora 36

### LINKED ISSUE #1886: Bump submariner images to F35 (or F36)
Currently the images are on F34 which is EOL since 2022-06-07 - https://docs.fedoraproject.org/en-US/releases/eol/

We should bump to F35 (or F36) to keep images up to date and secure

### PR DESCRIPTION
**Pull request by skitt**
See individual commits.

Depends on #1885.
Fixes #1886.

### CODE REVIEW

**Comment by skitt** [comment]
This fails because of `iptables` changes.

**Comment by nyechiel** [comment]
@skitt are we planning to get this done for 0.13? The PR is up for review in the 0.13 board but the linked issue is in the future backlog.

**Comment by skitt** [comment]
> @skitt are we planning to get this done for 0.13? The PR is up for review in the 0.13 board but the linked issue is in the future backlog.

We can discuss it in the calls next week, but I’d like to get this into 0.13 to avoid a release with already-obsolete base images.

**Review by mkolesnik — APPROVED** [review]
LGTM

**Comment by nyechiel** [comment]
@sridhargaddam can you review/approve please?

**Review by dfarrell07 — COMMENTED** [review]
In a commit message, you say

> We can do the same parsing using bash's builting getopt, so do that
instead.

I think you mean `getopts` here. As we're actually moving from `getopt`, I think the difference between the two is significant enough to fix.

> We can do the same parsing using bash's built-in getopts, so do that
instead.

**Review by dfarrell07 — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]
LGTM

**Pull request merged**
