### PR TITLE
Rename submariner image to submariner-gateway

### PR DESCRIPTION
**Pull request by mangelajo**
The old image will be released in parallel for a while, during
the transition.

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

### CODE REVIEW

**Review by SteveMattar — APPROVED** [review]

**Comment by skitt** [comment]
It seems the shared `Makefile.images` doesn’t handle symlinks very well...

**Comment by skitt** [comment]
> It seems the shared `Makefile.images` doesn’t handle symlinks very well...

Fixed by https://github.com/submariner-io/shipyard/pull/459.

**Comment by mangelajo** [comment]
@tpantelis ping ^

**Comment by mangelajo** [comment]
@skitt ping ^

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
