### PR TITLE
Backport: Ensure that vx-submariner interface is up (#1284)

### PR DESCRIPTION
**Pull request by sridhargaddam**
Fixes issue: https://github.com/submariner-io/submariner/issues/1275
Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

(cherry picked from commit e57ecd99feb27d4a2e9e014a2db85f588d9abfa0)

### CODE REVIEW

**Comment by sridhargaddam** [comment]
@mangelajo @skitt @tpantelis Is this some known issue?
E2e tests are failing for an unrelated error
```
[cluster3] Error: serviceaccounts "default" already exists
make[1]: *** [/opt/shipyard/Makefile.inc:45: deploy] Error 1
make: *** [/opt/shipyard/Makefile.inc:49: e2e] Error 2
```

**Review by tpantelis — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]

**Comment by mangelajo** [comment]
Ok, we need to figure out what's wrong with CI here.

**Comment by mangelajo** [comment]
@sridhargaddam can we rebase this one?, github is not showing the button.

**Comment by mangelajo** [comment]
Ah wait, this is release-0.8, it's probably up to date.

**Comment by mangelajo** [comment]
oh @sridhargaddam you backported on top of release-0.8, it shall be release-0.9

**Pull request merged**
